#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cmd2
Version  : 0.9.6
Release  : 40
URL      : https://files.pythonhosted.org/packages/21/80/a93427ed96b700d08200520fe318438ae6c257103941cd18ca1a8325a49a/cmd2-0.9.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/21/80/a93427ed96b700d08200520fe318438ae6c257103941cd18ca1a8325a49a/cmd2-0.9.6.tar.gz
Summary  : cmd2 - a tool for building interactive command line applications in Python
Group    : Development/Tools
License  : MIT
Requires: cmd2-license = %{version}-%{release}
Requires: cmd2-python = %{version}-%{release}
Requires: cmd2-python3 = %{version}-%{release}
Requires: attrs
Requires: colorama
Requires: contextlib2
Requires: pyperclip
Requires: pyreadline
Requires: typing
Requires: wcwidth
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : virtualenv

%description
it quick and easy for developers to build feature-rich and user-friendly interactive command line applications.  It
        provides a simple API which is an extension of Python's built-in cmd module.  cmd2 provides a wealth of features on top
        of cmd to make your life easier and eliminates much of the boilerplate code which would be necessary when using cmd.

%package license
Summary: license components for the cmd2 package.
Group: Default

%description license
license components for the cmd2 package.


%package python
Summary: python components for the cmd2 package.
Group: Default
Requires: cmd2-python3 = %{version}-%{release}

%description python
python components for the cmd2 package.


%package python3
Summary: python3 components for the cmd2 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cmd2 package.


%prep
%setup -q -n cmd2-0.9.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539661842
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cmd2
cp LICENSE %{buildroot}/usr/share/package-licenses/cmd2/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cmd2/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
